defaults:
  - base_config
  - _self_

model:
  pretrained_model_name_or_path: "toshi456/llava-jp-1.3b-v1.1"

wandb:
 log: true
 entity: "toshi_456"
 project: "heron-leaderboard"
 run_name: "llava-jp-1.3b-v1.1"